const lidwoordenLijst = {
  de: {
    "Vruchten, bomen, planten": [
      "appel",
      "banaan",
      "kers",
      "peer",
      "mango",
      "citroen",
      "sinaasappel",
      "perzik",
      "druif",
      "watermeloen",
      "ananas",
      "eik",
      "beuk",
      "spar",
      "roos",
      "tulp",
      "zonnebloem",
      "orchidee",
      "palm",
      "cactus",
      "aardbei",
      "wilg",
      "linde",
      "avocado",
      "kastanjeboom",
      "azalea",
      "vlinderstruik",
      "geranium",
      "papaja"
    ],
    "Namen van rivieren, bergen, zeeën, oceanen, straten": [
      "Maas",
      "Rijn",
      "Schelde",
      "Donau",
      "Nijl",
      "Amazone",
      "Himalaya",
      "Alpen",
      "Pyreneeën",
      "Noordzee",
      "Stille Oceaan",
      "Middellandse Zee",
      "Kerkstraat",
      "Dorpsstraat",
      "Mississippi",
      "Atlantische Oceaan",
      "Ganges",
      "Jangtse",
      "Eufraat",
      "Tigris",
      "Mount Everest",
      "Mount Kilimanjaro",
      "Andes",
      "Zwarte Zee",
      "Oeral",
      "Ierse Zee",
      "Beringzee",
      "Kalverstraat",
      "Damrak",
      "Oostzee"
    ],
    "Woorden op -heid": [
      "waarheid",
      "vrijheid",
      "gezondheid",
      "schoonheid",
      "snelheid",
      "eerlijkheid",
      "mogelijkheid",
      "zekerheid",
      "veiligheid",
      "duidelijkheid",
      "bekendheid",
      "werkelijkheid",
      "moeilijkheid",
      "geschiktheid",
      "tevredenheid",
      "nuttigheid",
      "beleefdheid",
      "gemeenheid",
      "leegheid",
      "traagheid",
      "afhankelijkheid",
      "volledigheid",
      "zelfstandigheid",
      "voorzichtigheid",
      "onzekerheid",
      "drukheid",
      "volwassenheid",
      "afwezigheid",
      "aanwezigheid",
      "correctheid"
    ],
    "Woorden op -ing": [
      "opening",
      "vergadering",
      "beslissing",
      "verandering",
      "behandeling",
      "betaling",
      "uitdaging",
      "ontmoeting",
      "scheiding",
      "beweging",
      "werking",
      "onderbreking",
      "aankondiging",
      "opleiding",
      "samenwerking",
      "aanmelding",
      "afmelding",
      "boeking",
      "verwijdering",
      "toelating",
      "vertaling",
      "verzameling",
      "afsluiting",
      "waarschuwing",
      "voorbereiding",
      "bevestiging",
      "goedkeuring",
      "bestemming",
      "versiering",
      "opsomming"
    ],
    "Woorden op -teit": [
      "universiteit",
      "kwaliteit",
      "realiteit",
      "activiteit",
      "passiviteit",
      "identiteit",
      "mentaliteit",
      "specialiteit",
      "brutaliteit",
      "creativiteit",
      "objectiviteit",
      "subjectiviteit",
      "stabiliteit",
      "flexibiliteit",
      "vitaliteit",
      "formaliteit",
      "nationaliteit",
      "originaliteit",
      "sensualiteit",
      "neutraliteit",
      "relativiteit",
      "causaliteit",
      "muzikaliteit",
      "illegaliteit",
      "legaliteit",
      "productiviteit",
      "spontaniteit",
      "effectiviteit",
      "intensiteit",
      "generositeit"
    ],

    // 6) Woorden op -nis (9 woorden)
    "Woorden op -nis": [
      "kennis",
      "gebeurtenis",
      "erfenis",
      "belevenis",
      "droefenis",
      "belijdenis",
      "bekentenis",
      "getuigenis",
      "hechtenis",
      "vergiffenis",
      "duisternis",
      "bemoeienis",
      "vernis",
      "verbintenis",
      "gevangenis",
      "schennis",
      "heugenis",
      "ergernis",
      "betekenis",
      "treurnis",
      "vuilnis",
      "geheimenis",
      "nagedachtenis",
      "geschiedenis",
      "muurnis",
      "schuilnis",
      "schemernis",
      "reddenis",
      "vergetenis",
      "verdoemenis"
    ],
    "Woorden op -st": [
      "kunst",
      "dienst",
      "oogst",
      "vorst",
      "winst",
      "troost",
      "rest",
      "kast",
      "angst",
      "gunst",
      "komst",
      "dorst",
      "worst",
      "nest",
      "mest",
      "test",
      "feest",
      "roest",
      "kist",
      "geest",
      "gast",
      "last",
      "post",
      "kost",
      "beest",
      "mist",
      "tekst",
      "pest",
      "onrust"
    ],
    "Woorden op -us": [
      "cursus",
      "status",
      "focus",
      "consensus",
      "bonus",
      "animus",
      "nexus",
      "terminus",
      "campus",
      "papyrus",
      "corpus",
      "virus",
      "circus",
      "venus",
      "blocus",
      "opus",
      "cultus",
      "apparatus",
      "exodus",
      "lotus",
      "modus",
      "incubus",
      "succubus",
      "postbus",
      "humus",
      "sinus",
      "tinnitus",
      "rhombus"
    ],
    "Woorden op -ade": [
      "salade",
      "promenade",
      "brigade",
      "aubade",
      "blokkade",
      "serenade",
      "parade",
      "limonade",
      "tirade",
      "barricade",
      "escalade",
      "marmelade",
      "ambassade",
      "arcade",
      "façade",
      "balustrade",
      "nomade",
      "cascade",
      "roulade",
      "chocolade",
      "spade",
      "boutade",
      "stade",
      "cavalcade",
      "croustade",
      "palissade",
      "fusillade",
      "renegade"
    ],
    "Woorden op -age": [
      "bagage",
      "etalage",
      "stage",
      "ravage",
      "reportage",
      "sabotage",
      "entourage",
      "persiflage",
      "collage",
      "drainage",
      "assemblage",
      "remontage",
      "curage",
      "hommage",
      "passage",
      "massage",
      "soutirage",
      "mirage",
      "vernissage",
      "bandage",
      "dosage",
      "voyage",
      "dommage",
      "arrimage",
      "tirage",
      "garage",
      "barrage",
      "fromage",
      "visage",
      "menage"
    ],

    "Woorden op -ine": [
      "discipline",
      "machine",
      "adrenaline",
      "heroïne",
      "vitamine",
      "margarine",
      "benzine",
      "praline",
      "gelatine",
      "routine",
      "turbine",
      "morfine",
      "codeïne",
      "cafeïne",
      "vitrine",
      "paraffine",
      "crinoline",
      "kinine",
      "valine",
      "leucine",
      "isoleucine",
      "methionine",
      "serine",
      "glycine",
      "strychnine",
      "mezzanine",
      "keratine",
      "histamine",
      "kerosine"
    ],
    "Woorden op -se": [
      "fase",
      "interesse",
      "analyse",
      "diagnose",
      "hypothese",
      "franchise",
      "oase",
      "prognose",
      "nuance",
      "synthese",
      "these",
      "expertise",
      "premisse",
      "remise",
      "polonaise",
      "suspense",
      "baisse",
      "metamorfose",
      "prothese",
      "finesse",
      "epifyse",
      "apofyse",
      "glycolyse",
      "lyse",
      "hypofyse",
      "sclerose",
      "psychose",
      "ketose",
      "hypnose",
      "parese"
    ],
    "Woorden op -de": [
      "methode",
      "periode",
      "code",
      "schade",
      "fraude",
      "lade",
      "genade",
      "spade",
      "wade",
      "zonde",
      "mode",
      "roede",
      "waarde",
      "kade",
      "bede",
      "vrede",
      "rede",
      "dode",
      "orde",
      "horde",
      "garde",
      "schede",
      "zijde",
      "kunde",
      "node",
      "vreugde"
    ],
    "Woorden op -iek": [
      "techniek",
      "politiek",
      "muziek",
      "rubriek",
      "kritiek",
      "grafiek",
      "kliniek",
      "esthetiek",
      "thematiek",
      "tactiek",
      "fysiek",
      "optiek",
      "retoriek",
      "symboliek",
      "toniek",
      "komiek",
      "ethiek",
      "poëtiek",
      "lyriek",
      "didactiek",
      "fonetiek",
      "statistiek",
      "diëtiek",
      "polemiek",
      "romantiek",
      "aerodynamiek",
      "elektroniek",
      "cybernetiek",
      "kinetiek",
      "haptiek"
    ],
    "Woorden op -theek": [
      "bibliotheek",
      "discotheek",
      "apotheek",
      "videotheek",
      "mediatheek",
      "ludotheek",
      "fonotheek",
      "fototheek",
      "kartotheek",
      "hortotheek",
      "phytotheek",
      "vinotheek"
    ],
    "Woorden op -ische": [
      "romantische",
      "kritische",
      "economische",
      "historische",
      "artistieke",
      "logische",
      "technische",
      "psychologische",
      "filosofische",
      "academische",
      "politieke",
      "dynamische",
      "grammatische",
      "automatische",
      "synthetische",
      "sympathische",
      "antropologische",
      "theologische",
      "archeologische",
      "didactische",
      "demografische",
      "geografische",
      "sociologische",
      "statistische",
      "praktische",
      "dialectische",
      "systematische",
      "energetische",
      "magische",
      "metafysische"
    ],
    "Mensen": [
      "man",
      "vrouw",
      "jongen",
      "vader",
      "moeder",
      "oom",
      "tante",
      "leraar",
      "lerares",
      "dokter",
      "tandarts",
      "chauffeur",
      "bakker",
      "verkoper",
      "verpleegster",
      "politieagent",
      "student",
      "advocate",
      "boer",
      "schilder",
      "directeur",
      "secretaris",
      "kapper",
      "kassamedewerker",
      "piloot",
      "ingenieur",
      "kok",
      "manager",
      "receptionist",
      "journalist"
      ],

    "Uitzondering op de regel Woorden op -um": [
      "datum" // Это "de datum", а не "het datum"
    ]
  },

  het: {
    "Namen van talen": [
      "Nederlands",
      "Engels",
      "Frans",
      "Duits",
      "Spaans",
      "Italiaans",
      "Portugees",
      "Russisch",
      "Chinees",
      "Japans",
      "Arabisch",
      "Grieks"
    ],

    // 2) Sporten en spelletjes (11 woorden)
    "Sporten en spelletjes": [
      "voetbal",
      "basketbal",
      "handbal",
      "honkbal",
      "schaken",
      "dammen",
      "tennis",
      "badminton",
      "boksen",
      "wielrennen",
      "schaatsen"
    ],

    // 3) Verkleinwoorden (diminutieven) (20 woorden)
    "Verkleinwoorden": [
      "boekje",
      "plantje",
      "autootje",
      "huisje",
      "bloemetje",
      "kindje",
      "hondje",
      "katje",
      "potloodje",
      "pennetje",
      "boompje",
      "ijsje",
      "briefje",
      "schaapje",
      "bedje",
      "kopje",
      "hapje",
      "feestje",
      "kaartje",
      "meisje"
    ],

    // 4) Metalen (10 woorden)
    "Metalen": [
      "goud",
      "zilver",
      "ijzer",
      "koper",
      "brons",
      "tin",
      "lood",
      "staal",
      "aluminium",
      "nikkel"
    ],

    // 5) Windrichtingen (4 woorden)
    "Windrichtingen": [
      "noorden",
      "oosten",
      "zuiden",
      "westen"
    ],

    // 6) Woorden op -isme (10 woorden)
    "Woorden op -isme": [
      "communisme",
      "kapitalisme",
      "socialisme",
      "liberalisme",
      "feminisme",
      "modernisme",
      "impressionisme",
      "expressionisme",
      "atheïsme",
      "boeddhisme"
    ],

    // 7) Werkwoorden als zelfstandige naamwoorden (15 woorden)
    "Werkwoorden als zn": [
      "eten",
      "drinken",
      "slapen",
      "lopen",
      "zwemmen",
      "rijden",
      "spreken",
      "lachen",
      "huilen",
      "lezen",
      "schrijven",
      "koken",
      "werken",
      "studeren",
      "sporten"
    ],

    // 8) Woorden die eindigen op -um (10 woorden)
    "Woorden op -um": [
      "museum",
      "centrum",
      "forum",
      "universum",
      "spectrum",
      "album",
      "stadium",
      "minimum",
      "maximum",
      "medium"
    ],

    // 9) Abstract/ontelbaar (20 woorden)
    "Abstract/ontelbaar": [
      "nieuws",
      "advies",
      "bewijs",
      "ijs",
      "gereedschap",
      "speelgoed",
      "verkeer",
      "geluk",
      "verdriet",
      "ongeluk",
      "haar",
      "leven",
      "onderwijs",
      "resultaat",
      "onderzoek",
      "inzicht",
      "gesprek",
      "vertrouwen",
      "gedrag",
      "geloof"
    ],

    // 10) Maten, getallen, collectieven (15 woorden)
    "Maten, getallen, collectieven": [
      "dozijn",
      "stel",
      "paar",
      "miljoen",
      "miljard",
      "procent",
      "individu",
      "ding",
      "detail",
      "woord",
      "gevoel",
      "beeld",
      "gebrek",
      "genot",
      "eind"
    ],

    // 11) Geografisch / Plaatsen (15 woorden)
    "Plaatsen (onzijdig)": [
      "station",
      "platteland",
      "bos",
      "strand",
      "dal",
      "meer",
      "kanaal",
      "dorp",
      "land",
      "continent",
      "gebied",
      "pad",
      "plein",
      "loket",
      "monument"
    ],

    // 12) Diversen (58 woorden) – чтобы суммарно получить 200 "het"-слов
    "Diversen": [
      "boek",
      "dak",
      "glas",
      "verhaal",
      "verschil",
      "plafond",
      "venster",
      "raam",
      "gordijn",
      "vlees",
      "fruit",
      "snoep",
      "sap",
      "mes",
      "bord",
      "punt",
      "moment",
      "uur",
      "jaar",
      "weekend",
      "probleem",
      "programma",
      "systeem",
      "product",
      "project",
      "concept",
      "contact",
      "akkoord",
      "gebruik",
      "bereik",
      "domein",
      "bestuur",
      "bevel",
      "publiek",
      "volk",
      "gevolg",
      "effect",
      "aspect",
      "object",
      "subject",
      "accent",
      "proces",
      "virus",
      "medicijn",
      "recept",
      "hoofdstuk",
      "rijbewijs",
      "paspoort",
      "nadeel",
      "voordeel",
      "getal",
      "nummer",
      "lied",
      "toneel",
      "concert",
      "evenement",
      "feest",
      "seizoen"
      ],
  }
};

// console.log(getRandomWord(rules));
function getRandomLidWord(rules) {
  const possibleWords = [];

  for (const article in lidwoordenLijst) {
    if (!rules[article]) continue;
    for (const category in lidwoordenLijst[article]) {
      if (!rules[article][category]) continue;
      lidwoordenLijst[article][category].forEach((woord) => {
        possibleWords.push({
          lidwoord: article,
          woord,
          waarom: category
        });
      });
    }
  }

  if (!possibleWords.length) {
    return {
      lidwoord: "",
      woord: "Geen woorden beschikbaar",
      waarom: ""
    };
  }

  return possibleWords[Math.floor(Math.random() * possibleWords.length)];
}

export {lidwoordenLijst, getRandomLidWord};