const ua = {
  "nietnormaalwerkwoordenovt": "Неправильні дієслова в OVT",
  "onregelmatigewerkwoordenmoetjevertalen": "Неправильні дієслова потрібно перекласти",
  "gaterug": "Повернутися",
  "lidwoorden": "Артиклі",
  "kieshetjuistelidwoordvoorhetwoord": "Виберіть правильний артикль для слова",
  "Probeer het artikel voor het woord te raden door op de of het te klikken": "Спробуйте вгадати артикль для слова, натиснувши на de або het",
  "nieuwwoord": "Нове слово",
  "deofhet?hoebepaaljehetlidwoord?inhetnederlandszijnertweelidwoorden:deenhet.demeestewoordenkrijgendemaarsommigecategorieënkrijgenaltijdhet.doordezeregelstelerenkunjemakkelijkerhetjuistelidwoordkiezen.wanneergebruikjede?vruchtenbomenenplantenvoorbeelden:deappeldebanaandeeikderoosnamenvanrivierenbergenheuvelszeeënoceanenenstratenvoorbeelden:demaasderijndealpendemiddellandsezeedekalverstraatwoordendieeindigenopheidingteitnisstusadeageinesedeiektheekischevoorbeelden:devrijheiddeopeningdeuniversiteitdekennisdekunstdecursusdesaladedebagagededisciplinedefasedemethodedemuziekdebibliotheekderomantischemensenenberoepenvoorbeelden:demandevrouwdeleraardedoktermeestemeervoudenvoorbeelden:dehuizendeboekendeauto’swanneergebruikjehet?namenvantalenvoorbeelden:hetnederlandshetengelshetfranssportenenspelletjesvoorbeelden:hetvoetbalhetschakenhetkaartspelverkleinwoorden(jetjeetjepjempje)voorbeelden:hetboekjehethuisjehetkindjemetalenenmaterialenvoorbeelden:hetgoudhetzilverhetijzerwindrichtingenvoorbeelden:hetnoordenhetzuidenhetwestenwoordenopismementumselschapvoorbeelden:hetcommunismehetargumenthetmuseumhetlandschapwerkwoordenalszelfstandignaamwoordvoorbeelden:hetetenhetslapenhetwerkenabstracteenontelbarebegrippenvoorbeelden:hetnieuwshetadvieshetgelukhetverdrietnamenvanlandenstedenencontinentenvoorbeelden:hetnederlandhetbrusselheteuropa(maar:deverenigdestatendefilipijnen)doordezeregelstoetepassenkunjebeterinschattenwelklidwoordeenwoordkrijgt.erzijnuitzonderingenmaardezerichtlijnenhelpenbijdemeestewoorden.": "De чи Het? Як визначити артикль?\n\nУ нідерландській мові є два означені артиклі: de та het. Більшість слів отримують de, але деякі категорії завжди використовують het. Вивчаючи ці правила, ви зможете легше вибрати правильний артикль.\n\nКоли використовувати de?\n\n- Фрукти, дерева та рослини\nПриклади: de appel (яблуко), de banaan (банан), de eik (дуб), de roos (троянда)\n\n- Назви річок, гір, пагорбів, морів, океанів та вулиць\nПриклади: de Maas (Маас), de Rijn (Рейн), de Alpen (Альпи), de Middellandse Zee (Середземне море), de Kalverstraat (Кальверстрат)\n\n- Слова, що закінчуються на -heid, -ing, -teit, -nis, -st, -us, -ade, -age, -ine, -se, -de, -iek, -theek, -ische\nПриклади:\n- de vrijheid (свобода), de opening (відкриття), de universiteit (університет), de kennis (знання), de kunst (мистецтво), de cursus (курс)\n- de salade (салат), de bagage (багаж), de discipline (дисципліна), de fase (фаза), de methode (метод), de muziek (музика), de bibliotheek (бібліотека), de romantische (романтичний)\n\n- Люди та професії\nПриклади: de man (чоловік), de vrouw (жінка), de leraar (вчитель), de dokter (лікар)\n\n- Більшість множинних форм\nПриклади: de huizen (будинки), de boeken (книги), de auto’s (автомобілі)\n\nКоли використовувати het?\n\n- Назви мов\nПриклади: het Nederlands (нідерландська), het Engels (англійська), het Frans (французька)\n\n- Спорт і ігри\nПриклади: het voetbal (футбол), het schaken (шахи), het kaartspel (карткова гра)\n\n- Зменшувальні форми (-je, -tje, -etje, -pje, -mpje)\nПриклади: het boekje (книжечка), het huisje (будиночок), het kindje (дитинка)\n\n- Метали та матеріали\nПриклади: het goud (золото), het zilver (срібло), het ijzer (залізо)\n\n- Сторони світу\nПриклади: het noorden (північ), het zuiden (південь), het westen (захід)\n\n- Слова, що закінчуються на -isme, -ment, -um, -sel, -schap\nПриклади: het communisme (комунізм), het argument (аргумент), het museum (музей), het landschap (пейзаж)\n\n- Дієслова, використані як іменники\nПриклади: het eten (їжа), het slapen (сон), het werken (робота)\n\n- Абстрактні та незліченні поняття\nПриклади: het nieuws (новини), het advies (порада), het geluk (щастя), het verdriet (смуток)\n\n- Назви країн, міст та континентів\nПриклади: het Nederland (Нідерланди), het Brussel (Брюссель), het Europa (Європа) (але: de Verenigde Staten (США), de Filipijnen (Філіппіни))\n\nДотримуючись цих правил, ви зможете краще визначати правильний артикль для слова. Існують винятки, але ці вказівки допомагають у більшості випадків.",
  "oekraïens": "Українська",
  "start": "Старт",
  "vruchtenbomenplanten": "Фрукти, дерева, рослини",
  "namenvanrivierenbergenzeeënoceanenstraten": "Назви річок, гір, морів, океанів, вулиць",
  "woordenopheid": "Слова на -heid",
  "woordenoping": "Слова на -ing",
  "woordenopteit": "Слова на -teit",
  "woordenopnis": "Слова на -nis",
  "woordenopst": "Слова на -st",
  "woordenopus": "Слова на -us",
  "woordenopade": "Слова на -ade",
  "woordenopage": "Слова на -age",
  "woordenopine": "Слова на -ine",
  "woordenopse": "Слова на -se",
  "woordenopde": "Слова на -de",
  "woordenopiek": "Слова на -iek",
  "woordenoptheek": "Слова на -theek",
  "woordenopische": "Слова на -ische",
  "mensen": "Люди",
  "uitzonderingopderegelwoordenopum": "Виняток з правила слів на -um",
  "namenvantalen": "Назви мов",
  "sportenenspelletjes": "Види спорту та ігри",
  "verkleinwoorden": "Зменшувальні слова",
  "metalen": "Метали",
  "windrichtingen": "Напрями вітру",
  "woordenopisme": "Слова на -isme",
  "werkwoordenalszn": "Дієслова як іменники",
  "woordenopum": "Слова на -um",
  "Abstract/ontelbaar": "Абстрактні/необчислювані слова",
  "matengetallencollectieven": "Одиниці вимірювання, числа, колективи",
  "plaatsenonzijdig": "Географічні місця (середній рід)",
  "diversen": "Треба знати",
  "appel": "яблуко",
  "banaan": "банан",
  "kers": "вишня",
  "peer": "груша",
  "mango": "манго",
  "citroen": "лимон",
  "sinaasappel": "апельсин",
  "perzik": "персик",
  "druif": "виноград",
  "watermeloen": "кавун",
  "ananas": "ананас",
  "eik": "дуб",
  "beuk": "бук",
  "spar": "ялина",
  "roos": "троянда",
  "tulp": "тюльпан",
  "zonnebloem": "соняшник",
  "orchidee": "орхідея",
  "palm": "пальма",
  "cactus": "кактус",
  "aardbei": "полуниця",
  "wilg": "верба",
  "linde": "липа",
  "avocado": "авокадо",
  "kastanjeboom": "каштан",
  "azalea": "азалія",
  "vlinderstruik": "буддлея",
  "geranium": "герань",
  "papaja": "папая",

  "Maas": "Маас",
  "Rijn": "Рейн",
  "Schelde": "Шельда",
  "Donau": "Дунай",
  "Nijl": "Ніл",
  "Amazone": "Амазонка",
  "Himalaya": "Гімалаї",
  "Alpen": "Альпи",
  "Pyreneeën": "Піренеї",
  "Noordzee": "Північне море",
  "Stille Oceaan": "Тихий океан",
  "Middellandse Zee": "Середземне море",
  "Kerkstraat": "Керкстрат",
  "Dorpsstraat": "Дорпстрат",
  "Mississippi": "Міссісіпі",
  "Atlantische Oceaan": "Атлантичний океан",
  "Ganges": "Ганг",
  "Jangtse": "Янцзи",
  "Eufraat": "Євфрат",
  "Tigris": "Тигр",
  "Mount Everest": "Еверест",
  "Mount Kilimanjaro": "Кіліманджаро",
  "Andes": "Анди",
  "Zwarte Zee": "Чорне море",
  "Oeral": "Урал",
  "Ierse Zee": "Ірландське море",
  "Beringzee": "Берингове море",
  "Kalverstraat": "Калверстрат",
  "Damrak": "Дамрак",
  "Oostzee": "Балтійське море",

  "waarheid": "правда",
  "vrijheid": "свобода",
  "gezondheid": "здоров'я",
  "schoonheid": "краса",
  "snelheid": "швидкість",
  "eerlijkheid": "чесність",
  "mogelijkheid": "можливість",
  "zekerheid": "певність",
  "veiligheid": "безпека",
  "duidelijkheid": "чіткість",
  "bekendheid": "відомість",
  "werkelijkheid": "реальність",
  "moeilijkheid": "складність",
  "geschiktheid": "придатність",
  "tevredenheid": "задоволеність",
  "nuttigheid": "корисність",
  "beleefdheid": "ввічливість",
  "gemeenheid": "підлість",
  "leegheid": "порожнеча",
  "traagheid": "повільність",
  "afhankelijkheid": "залежність",
  "volledigheid": "повнота",
  "zelfstandigheid": "самостійність",
  "voorzichtigheid": "обережність",
  "onzekerheid": "невпевненість",
  "drukheid": "метушливість",
  "volwassenheid": "зрілість",
  "afwezigheid": "відсутність",
  "aanwezigheid": "присутність",
  "correctheid": "правильність",

  "opening": "відкриття",
  "vergadering": "збори",
  "beslissing": "рішення",
  "verandering": "зміна",
  "behandeling": "лікування / поводження",
  "betaling": "оплата",
  "uitdaging": "виклик",
  "ontmoeting": "зустріч",
  "scheiding": "розлучення / поділ",
  "beweging": "рух",
  "werking": "дія",
  "onderbreking": "перерва",
  "aankondiging": "оголошення",
  "opleiding": "освіта / навчання",
  "samenwerking": "співпраця",
  "aanmelding": "реєстрація",
  "afmelding": "відмова від реєстрації",
  "boeking": "бронювання",
  "verwijdering": "видалення",
  "toelating": "допуск",
  "vertaling": "переклад",
  "verzameling": "колекція",
  "afsluiting": "закриття",
  "waarschuwing": "попередження",
  "voorbereiding": "підготовка",
  "bevestiging": "підтвердження",
  "goedkeuring": "схвалення",
  "bestemming": "призначення / місце призначення",
  "versiering": "прикраса",
  "opsomming": "перелік",

  "universiteit": "університет",
  "kwaliteit": "якість",
  "realiteit": "реальність",
  "activiteit": "діяльність",
  "passiviteit": "пасивність",
  "identiteit": "ідентичність",
  "mentaliteit": "менталітет",
  "specialiteit": "спеціальність",
  "brutaliteit": "зухвалість",
  "creativiteit": "креативність",
  "objectiviteit": "об'єктивність",
  "subjectiviteit": "суб'єктивність",
  "stabiliteit": "стабільність",
  "flexibiliteit": "гнучкість",
  "vitaliteit": "життєздатність",
  "formaliteit": "формальність",
  "nationaliteit": "національність",
  "originaliteit": "оригінальність",
  "sensualiteit": "чуттєвість",
  "neutraliteit": "нейтральність",
  "relativiteit": "відносність",
  "causaliteit": "причинність",
  "muzikaliteit": "музикальність",
  "illegaliteit": "нелегальність",
  "legaliteit": "законність",
  "productiviteit": "продуктивність",
  "spontaniteit": "спонтанність",
  "effectiviteit": "ефективність",
  "intensiteit": "інтенсивність",
  "generositeit": "щедрість",

  "kennis": "знання",
  "gebeurtenis": "подія",
  "erfenis": "спадок",
  "belevenis": "пригодa / враження",
  "droefenis": "печаль",
  "belijdenis": "сповідь / визнання",
  "bekentenis": "зізнання",
  "getuigenis": "свідчення",
  "hechtenis": "ув'язнення",
  "vergiffenis": "прощення",
  "duisternis": "темрява",
  "bemoeienis": "втручання",
  "vernis": "лак (у контексті)",
  "verbintenis": "зобов'язання / зв'язок",
  "gevangenis": "в'язниця",
  "schennis": "наруга",
  "heugenis": "пам'ять (устар.)",
  "ergernis": "роздратування",
  "betekenis": "значення",
  "treurnis": "смуток",
  "vuilnis": "сміття",
  "geheimenis": "таємниця (застар.)",
  "nagedachtenis": "пам'ять (про когось)",
  "geschiedenis": "історія",
  "muurnis": "ніша в стіні",
  "schuilnis": "притулок / сховок",
  "schemernis": "сутінки (застар.)",
  "reddenis": "порятунок (застар.)",
  "vergetenis": "забуття",
  "verdoemenis": "прокляття / осудження",

  "kunst": "мистецтво",
  "dienst": "служба / послуга",
  "oogst": "врожай",
  "vorst": "мороз / князь (контекст!)",
  "winst": "прибуток / виграш",
  "troost": "втіха",
  "rest": "залишок",
  "kast": "шафа",
  "angst": "страх",
  "gunst": "послуга / ласка",
  "komst": "прибуття / прихід",
  "dorst": "спрага",
  "worst": "ковбаса",
  "nest": "гніздо",
  "mest": "гній",
  "test": "тест / випробування",
  "feest": "свято",
  "roest": "іржа",
  "kist": "скриня / труна (контекст!)",
  "geest": "дух / розум",
  "gast": "гість",
  "last": "тягар / вантаж",
  "post": "пошта / посада (контекст!)",
  "kost": "їжа / вартість (контекст!)",
  "beest": "звір / тварина",
  "mist": "туман",
  "tekst": "текст",
  "pest": "чума / знущання (контекст)",
  "onrust": "неспокій",

  "cursus": "курс",
  "status": "статус",
  "focus": "фокус / увага",
  "consensus": "консенсус",
  "bonus": "бонус",
  "animus": "ворожість / настрій (лат.)",
  "nexus": "зв'язок (лат.)",
  "terminus": "термінус / кінцева станція",
  "campus": "кампус",
  "papyrus": "папірус",
  "corpus": "корпус / зібрання текстів",
  "virus": "вірус",
  "circus": "цирк",
  "venus": "Венера",
  "blocus": "блокада (фр.)",
  "opus": "опус / твір",
  "cultus": "культ / поклоніння",
  "apparatus": "апарат / прилад",
  "exodus": "вихід / масове переселення",
  "lotus": "лотос",
  "modus": "спосіб / форма (лат.)",
  "incubus": "інкуб / нічний жах (міф.)",
  "succubus": "суккуб (міф.)",
  "postbus": "поштова скринька",
  "humus": "гумус",
  "sinus": "синус / пазуха",
  "tinnitus": "шум у вухах",
  "rhombus": "ромб",

  "salade": "салат",
  "promenade": "променад / прогулянка",
  "brigade": "бригада",
  "aubade": "ранкова серенада",
  "blokkade": "блокада",
  "serenade": "серенада",
  "parade": "парад",
  "limonade": "лимонад",
  "tirade": "тирада",
  "barricade": "барикада",
  "escalade": "ескалація / штурм",
  "marmelade": "мармелад",
  "ambassade": "посольство",
  "arcade": "аркада / галерея",
  "façade": "фасад",
  "balustrade": "балюстрада",
  "nomade": "кочівник (фр.)",
  "cascade": "каскад",
  "roulade": "рулада",
  "chocolade": "шоколад",
  "spade": "лопата (застар.)",
  "boutade": "дотеп / жарт (фр.)",
  "stade": "стадія (застар.)",
  "cavalcade": "кавалкада",
  "croustade": "крустад (фр. випічка)",
  "palissade": "паркан / палісад",
  "fusillade": "стрілянина (фр.)",
  "renegade": "ренегат / відступник",

  "bagage": "багаж",
  "etalage": "вітрина",
  "stage": "стажування / практика",
  "ravage": "руйнування",
  "reportage": "репортаж",
  "sabotage": "саботаж",
  "entourage": "оточення",
  "persiflage": "насмішка / пародія",
  "collage": "колаж",
  "drainage": "дренаж",
  "assemblage": "зібрання / монтаж",
  "remontage": "перезбір / ремонт (контекст)",
  "curage": "прочищення / очищення (фр.)",
  "hommage": "шана / homage",
  "passage": "прохід / уривок (текст)",
  "massage": "масаж",
  "soutirage": "зливання (техн.)",
  "mirage": "міраж",
  "vernissage": "вернісаж",
  "bandage": "бандаж / перев'язка",
  "dosage": "дозування",
  "voyage": "подорож",
  "dommage": "шкода / на жаль (фр.)",
  "arrimage": "кріплення вантажу (мор.)",
  "tirage": "тираж",
  "garage": "гараж",
  "barrage": "дамба / загата",
  "fromage": "сир (фр.)",
  "visage": "обличчя (фр.)",
  "menage": "управління господарством (фр.)",
  "discipline": "дисципліна",
  "machine": "машина",
  "adrenaline": "адреналін",
  "heroïne": "героїн",
  "vitamine": "вітамін",
  "margarine": "маргарин",
  "benzine": "бензин",
  "praline": "праліне",
  "gelatine": "желатин",
  "routine": "рутина",
  "turbine": "турбіна",
  "morfine": "морфін",
  "codeïne": "кодеїн",
  "cafeïne": "кофеїн",
  "vitrine": "вітрина",
  "paraffine": "парафін",
  "crinoline": "кринолін",
  "kinine": "хінін",
  "valine": "валін",
  "leucine": "лейцин",
  "isoleucine": "ізолейцин",
  "methionine": "метіонін",
  "serine": "серин",
  "glycine": "гліцин",
  "strychnine": "стрихнін",
  "mezzanine": "мезонін",
  "keratine": "кератин",
  "histamine": "гістамін",
  "kerosine": "гас",
  "fase": "фаза",
  "interesse": "інтерес",
  "analyse": "аналіз",
  "diagnose": "діагноз",
  "hypothese": "гіпотеза",
  "franchise": "франшиза",
  "oase": "оаза",
  "prognose": "прогноз",
  "nuance": "нюанс",
  "synthese": "синтез",
  "these": "теза",
  "expertise": "експертиза",
  "premisse": "передумова",
  "remise": "ремісія / або здача (залежить від контексту)",
  "polonaise": "полонез",
  "suspense": "напруга (у сюжеті)",
  "baisse": "зниження (фр., бірж.)",
  "metamorfose": "метаморфоза",
  "prothese": "протез",
  "finesse": "витонченість / тонкість",
  "epifyse": "епіфіз",
  "apofyse": "апофіз",
  "glycolyse": "гліколіз",
  "lyse": "лізис",
  "hypofyse": "гіпофіз",
  "sclerose": "склероз",
  "psychose": "психоз",
  "ketose": "кетоз",
  "hypnose": "гіпноз",
  "parese": "парез",
  "methode": "метод",
  "periode": "період",
  "code": "код",
  "schade": "шкода",
  "fraude": "шахрайство",
  "lade": "шухляда",
  "genade": "милість / пощада",
  "wade": "саван / (або мілководдя, контекст)",
  "zonde": "гріх",
  "mode": "мода",
  "roede": "прут / різка",
  "waarde": "цінність / вартість",
  "kade": "пристань / набережна",
  "bede": "благання",
  "vrede": "мир",
  "rede": "промова / розум (контекст)",
  "dode": "померлий",
  "orde": "порядок / орден",
  "horde": "орда / натовп",
  "garde": "гвардія / вінчик (кухонне приладдя)",
  "schede": "піхва / оболонка",
  "zijde": "шовк / сторона (контекст)",
  "kunde": "уміння / наука (контекст)",
  "node": "вузол / необхідність (застар.)",
  "vreugde": "радість",
  "techniek": "техніка",
  "politiek": "політика",
  "muziek": "музика",
  "rubriek": "рубрика",
  "kritiek": "критика",
  "grafiek": "графіка / графік",
  "kliniek": "клініка",
  "esthetiek": "естетика",
  "thematiek": "тематика",
  "tactiek": "тактика",
  "fysiek": "фізика (застар.) / фізичний (adj.)",
  "optiek": "оптика",
  "retoriek": "риторика",
  "symboliek": "символіка",
  "toniek": "тонік / тонічний засіб",
  "komiek": "комік",
  "ethiek": "етика",
  "poëtiek": "поетика",
  "lyriek": "лірика",
  "didactiek": "дидактика",
  "fonetiek": "фонетика",
  "statistiek": "статистика",
  "diëtiek": "дієтологія",
  "polemiek": "полеміка",
  "romantiek": "романтика",
  "aerodynamiek": "аеродинаміка",
  "elektroniek": "електроніка",
  "cybernetiek": "кібернетика",
  "kinetiek": "кінетика",
  "haptiek": "гаптика",
  "bibliotheek": "бібліотека",
  "discotheek": "дискотека",
  "apotheek": "аптека",
  "videotheek": "відеотека",
  "mediatheek": "медіатека",
  "ludotheek": "ігрова бібліотека",
  "fonotheek": "фонотека",
  "fototheek": "фототека",
  "kartotheek": "картотека",
  "hortotheek": "колекція рослин (садівнича)",
  "phytotheek": "фітотека",
  "vinotheek": "колекція вин (винний льох)",
  "romantische": "романтична",
  "kritische": "критична",
  "economische": "економічна",
  "historische": "історична",
  "artistieke": "артистична / мистецька",
  "logische": "логічна",
  "technische": "технічна",
  "psychologische": "психологічна",
  "filosofische": "філософська",
  "academische": "академічна",
  "politieke": "політична",
  "dynamische": "динамічна",
  "grammatische": "граматична",
  "automatische": "автоматична",
  "synthetische": "синтетична",
  "sympathische": "симпатична",
  "antropologische": "антропологічна",
  "theologische": "теологічна",
  "archeologische": "археологічна",
  "didactische": "дидактична",
  "demografische": "демографічна",
  "geografische": "географічна",
  "sociologische": "соціологічна",
  "statistische": "статистична",
  "praktische": "практична",
  "dialectische": "діалектична",
  "systematische": "систематична",
  "energetische": "енергетична",
  "magische": "магічна",
  "metafysische": "метафізична",
  "man": "чоловік",
  "vrouw": "жінка",
  "jongen": "хлопець / хлопчик",
  "vader": "батько",
  "moeder": "мати",
  "oom": "дядько",
  "tante": "тітка",
  "leraar": "вчитель",
  "lerares": "вчителька",
  "dokter": "лікар",
  "tandarts": "стоматолог",
  "chauffeur": "водій",
  "bakker": "пекар",
  "verkoper": "продавець",
  "verpleegster": "медсестра",
  "politieagent": "поліцейський",
  "student": "студент",
  "advocate": "адвокатка",
  "boer": "фермер",
  "schilder": "маляр / художник",
  "directeur": "директор",
  "secretaris": "секретар",
  "kapper": "перукар",
  "kassamedewerker": "касир",
  "piloot": "пілот",
  "ingenieur": "інженер",
  "kok": "кухар",
  "manager": "менеджер",
  "receptionist": "адміністратор (ресепшн)",
  "journalist": "журналіст",
  "datum": "дата",
  "Nederlands": "нідерландська",
  "Engels": "англійська",
  "Frans": "французька",
  "Duits": "німецька",
  "Spaans": "іспанська",
  "Italiaans": "італійська",
  "Portugees": "португальська",
  "Russisch": "російська",
  "Chinees": "китайська",
  "Japans": "японська",
  "Arabisch": "арабська",
  "Grieks": "грецька",
  "voetbal": "футбол",
  "basketbal": "баскетбол",
  "handbal": "гандбол",
  "honkbal": "бейсбол",
  "schaken": "шахи",
  "dammen": "шашки",
  "tennis": "теніс",
  "badminton": "бадмінтон",
  "boksen": "бокс",
  "wielrennen": "велоспорт",
  "schaatsen": "катання на ковзанах",
  "boekje": "книжечка",
  "plantje": "рослинка",
  "autootje": "машинка",
  "huisje": "будиночок",
  "bloemetje": "квіточка",
  "kindje": "дитятко",
  "hondje": "песик",
  "katje": "кошеня",
  "potloodje": "олівчик",
  "pennetje": "ручечка / маленька ручка",
  "boompje": "деревце",
  "ijsje": "морозиво (маленька порція)",
  "briefje": "листочок / записка",
  "schaapje": "овечка",
  "bedje": "ліжечко",
  "kopje": "чашечка",
  "hapje": "шматочок / перекус",
  "feestje": "вечірка",
  "kaartje": "квиточок / листівка",
  "meisje": "дівчинка",
  "goud": "золото",
  "zilver": "срібло",
  "ijzer": "залізо",
  "koper": "мідь",
  "brons": "бронза",
  "tin": "олово",
  "lood": "свинець",
  "staal": "сталь",
  "aluminium": "алюміній",
  "nikkel": "нікель",
  "noorden": "північ",
  "oosten": "схід",
  "zuiden": "південь",
  "westen": "захід",
  "communisme": "комунізм",
  "kapitalisme": "капіталізм",
  "socialisme": "соціалізм",
  "liberalisme": "лібералізм",
  "feminisme": "фемінізм",
  "modernisme": "модернізм",
  "impressionisme": "імпресіонізм",
  "expressionisme": "експресіонізм",
  "atheïsme": "атеїзм",
  "boeddhisme": "буддизм",
  "eten": "їжа (процес їсти)",
  "drinken": "пиття (процес пити)",
  "slapen": "сон (процес спати)",
  "lopen": "хід (процес іти)",
  "zwemmen": "плавання",
  "rijden": "їзда",
  "spreken": "мовлення",
  "lachen": "сміх",
  "huilen": "плач",
  "lezen": "читання",
  "schrijven": "писання",
  "koken": "готування",
  "werken": "робота",
  "studeren": "навчання",
  "sporten": "заняття спортом",
  "museum": "музей",
  "centrum": "центр",
  "forum": "форум",
  "universum": "всесвіт",
  "spectrum": "спектр",
  "album": "альбом",
  "stadium": "стадія / стадіон (застар. варіант)",
  "minimum": "мінімум",
  "maximum": "максимум",
  "medium": "середовище / носій (контекст)",
  "nieuws": "новини",
  "advies": "порада",
  "bewijs": "доказ",
  "ijs": "лід / морозиво (контекст)",
  "gereedschap": "інструмент / знаряддя",
  "speelgoed": "іграшки",
  "verkeer": "дорожній рух",
  "geluk": "щастя / вдача",
  "verdriet": "смуток",
  "ongeluk": "нещастя / аварія (контекст)",
  "haar": "волосся",
  "leven": "життя",
  "onderwijs": "освіта",
  "resultaat": "результат",
  "onderzoek": "дослідження",
  "inzicht": "розуміння / усвідомлення",
  "gesprek": "розмова",
  "vertrouwen": "довіра",
  "gedrag": "поведінка",
  "geloof": "віра",
  "dozijn": "дюжина",
  "stel": "пара / набір",
  "paar": "пара",
  "miljoen": "мільйон",
  "miljard": "мільярд",
  "procent": "відсоток",
  "individu": "особа / індивід",
  "ding": "річ",
  "detail": "деталь",
  "woord": "слово",
  "gevoel": "почуття",
  "beeld": "зображення / уява",
  "gebrek": "недолік / відсутність",
  "genot": "задоволення",
  "eind": "кінець",
  "station": "станція / вокзал",
  "platteland": "сільська місцевість",
  "bos": "ліс",
  "strand": "пляж",
  "dal": "долина",
  "meer": "озеро",
  "kanaal": "канал",
  "dorp": "село",
  "land": "країна / земля",
  "continent": "континент",
  "gebied": "територія",
  "pad": "стежка / шлях",
  "plein": "площа",
  "loket": "віконце (касa)",
  "monument": "пам'ятник / монумент",
  "boek": "книга",
  "dak": "дах",
  "glas": "скло / склянка",
  "verhaal": "історія / оповідь",
  "verschil": "різниця",
  "plafond": "стеля",
  "venster": "вікно (застар.)",
  "raam": "вікно",
  "gordijn": "штора",
  "vlees": "м'ясо",
  "fruit": "фрукти",
  "snoep": "цукерки",
  "sap": "сік",
  "mes": "ніж",
  "bord": "тарілка / дошка (контекст)",
  "punt": "точка / момент",
  "moment": "миттєвість / момент",
  "uur": "година",
  "jaar": "рік",
  "weekend": "вікенд",
  "probleem": "проблема",
  "programma": "програма",
  "systeem": "система",
  "product": "продукт",
  "project": "проєкт",
  "concept": "концепт / ідея",
  "contact": "контакт",
  "akkoord": "згода / акорд (муз.)",
  "gebruik": "використання",
  "bereik": "досяжність",
  "domein": "домен / сфера",
  "bestuur": "управління / правління",
  "bevel": "наказ",
  "publiek": "публіка / громадськість",
  "volk": "народ",
  "gevolg": "наслідок",
  "effect": "ефект",
  "aspect": "аспект",
  "object": "об'єкт",
  "subject": "суб'єкт",
  "accent": "акцент",
  "proces": "процес",
  "medicijn": "ліки",
  "recept": "рецепт",
  "hoofdstuk": "розділ",
  "rijbewijs": "водійське посвідчення",
  "paspoort": "паспорт",
  "nadeel": "недолік",
  "voordeel": "перевага",
  "getal": "число",
  "nummer": "номер",
  "lied": "пісня",
  "toneel": "сцена / театр (контекст)",
  "concert": "концерт",
  "evenement": "подія / захід",
  "seizoen": "пора року / сезон",
  "Alles": "Усi"
};

export default ua;
